version: "3.9"

services:
  cronosd:
    container_name: cronosd
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cronosd:latest
    restart: always
    volumes:
      - cronos_data:/root/.cronos/

volumes:
  cronos_data:
    driver_opts:
      type: none
      device: ${PWD}/cronos_data/
      o: bind
